### ISSUE TITLE
DON'T RUN THIS MALWARE ON YOUR SERVER

### ISSUE THREAD

**Issue by vitonsky** [healthyhost/audit-vps-script#4]
That's a friendly reminder for those who visit github to check source before run a random script from the internet on your machine.

The fact that you can't see any suspicious code in shell script from that repo does not mean nothing, since **code in current repository may be different of code that will be downloaded from server**.

Never run third party code from internet on your infrastructure - that's a first step to make your server more secure.

**Comment by JapSeyz** [comment]
Just out of curiosity, did you check the downloaded script before calling this malware?

You can check the downloaded scripts source code instead of running it directly - which gives the same security as auditing it on Github. 

Never run something that you or someone you trust hasn't audited, but also don't run around creating fear when there isn't any. General guidelines are fine, but what you are doing here is just fear-mongering...

PS. the way the download instruction is set up, you absolutely can check the code on Github: `$ curl -O https://raw.githubusercontent.com/healthyhost/audit-vps-script/main/audit.sh`

**Comment by kkyr** [comment]
@vitonsky please point out where the alleged malware is, whether on the GitHub version or on the one hosted on the server. Otherwise, I kindly ask that you refrain from making these baseless claims.

What @JapSeyz is right. There's nothing stopping you from reading the script you downloaded from the server before executing it (as you should). In fact, I might add a prompt in the script asking the user if they first read the script before executing it. Thank you for the inspiration!
